[en_US]
axiom = "Axiom"
postulate = "Postulate"
theorem = "Theorem"
lemma = "Lemma"
observation = "Observation"
proposition = "Proposition"
property = "Property"
claim = "Claim"
corollary = "Corollary"
definition = "Definition"
convention = "Convention"
example = "Example"
remark = "Remark"
note = "Note"
comment = "Comment"
proof = "Proof"
law = "Law"
principle = "Principle"

[zh_CN]
axiom = "公理"
postulate = "假定"
theorem = "定理"
lemma = "引理"
observation = "观察"
proposition = "命题"
property = "性质"
claim = "断言"
corollary = "推论"
definition = "定义"
convention = "约定"
example = "示例"
remark = "备考"
note = "注"
comment = "评论"
proof = "证"
law = "定律"
principle = "原理"